class IOManager
  include IOStates

  include TempScaleNames

  def initialize: () -> void

  def valid_scale?: (String scale) -> untyped

  def input_temp_value: () -> (nil | untyped)

  def check_correctness_input_value: (untyped temp_value_kelvin) -> untyped

  def input_scale: (String message) -> untyped

  def convert_again: () -> void

  def next_state: () -> void

  def print_result: (String message) -> untyped

  def start: () -> void
end
