class ScaleConverterFromKelvin
  include TempScaleNames

  def initialize: () -> untyped

  def convert: (untyped degree, untyped to_scale) -> untyped

  private

  def to_fahrenheit: (untyped degree) -> untyped

  def to_celsius: (untyped degree) -> untyped
end

